"""empty message

Revision ID: 48b937a669cb
Revises: 
Create Date: 2020-06-10 16:37:01.989808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b937a669cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('namespace_id', sa.INTEGER(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('final_auth_content', sa.String(length=1000), nullable=True),
    sa.Column('setting_auth_content', sa.String(length=1000), nullable=True),
    sa.Column('last_activity_on', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
