name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image And Publish to DockerHub
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build . --file docker/Dockerfile --tag liduote/svnadmin:latest
        docker login -u $USERNAME -p $PASSWORD
        docker push liduote/svnadmin:latest
